# Generated by Django 2.0 on 2018-03-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=50)),
                ('test_user', models.CharField(max_length=50)),
                ('lifting_time', models.DateTimeField()),
                ('simple_desc', models.CharField(max_length=100, null=True)),
                ('other_desc', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ModuleInfo',
                'verbose_name': '模块信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('pro_name', models.CharField(max_length=50)),
                ('responsible_name', models.CharField(max_length=20)),
                ('test_user', models.CharField(max_length=100)),
                ('dev_user', models.CharField(max_length=100)),
                ('publish_app', models.CharField(max_length=60)),
                ('simple_desc', models.CharField(max_length=100, null=True)),
                ('other_desc', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ProjectInfo',
                'verbose_name': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('belong_project', models.CharField(max_length=50)),
                ('include', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=20)),
                ('request', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo')),
            ],
            options={
                'db_table': 'TestCaseInfo',
                'verbose_name': '用例信息',
            },
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('belong_project', models.CharField(max_length=50)),
                ('belong_module', models.CharField(max_length=50)),
                ('reports', models.TextField()),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'TestReports',
                'verbose_name': '测试报告',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'UserInfo',
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=20)),
                ('type_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UserType',
                'verbose_name': '用户类型',
            },
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo'),
        ),
    ]
