# Generated by Django 2.0 on 2018-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinfo',
            options={'verbose_name': '模块信息'},
        ),
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'verbose_name': '项目信息'},
        ),
        migrations.AlterModelOptions(
            name='testcaseinfo',
            options={'verbose_name': '用例信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': '用户类型'},
        ),
    ]
