# Generated by Django 2.0.3 on 2018-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreports',
            name='report_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testreports',
            name='start_at',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
