# Generated by Django 2.0 on 2017-12-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('test_user', models.CharField(max_length=50)),
                ('lifting_time', models.DateTimeField()),
                ('simple_desc', models.CharField(max_length=100)),
                ('other_desc', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ModuleInfo',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.IntegerField(db_column='project_id', primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('responsible_name', models.CharField(max_length=20)),
                ('test_user', models.CharField(max_length=100)),
                ('dev_user', models.CharField(max_length=100)),
                ('publish_app', models.CharField(max_length=60)),
                ('simple_desc', models.CharField(max_length=100)),
                ('other_desc', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ProjectInfo',
            },
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='belong_project',
            field=models.ForeignKey(db_column='belong_project', on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo'),
        ),
    ]
