# Generated by Django 2.0.3 on 2018-06-08 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_auto_20180502_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('debugtalk', models.TextField()),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo')),
            ],
            options={
                'verbose_name': '公共字段表',
                'abstract': False,
                'db_table': 'BaseTable',
            },
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='include',
            field=models.CharField(max_length=400, null=True, verbose_name='包含config/test'),
        ),
    ]
