# Generated by Django 2.0 on 2018-01-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_testcaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinfo',
            name='setup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='teardown',
            field=models.TextField(null=True),
        ),
    ]
