# Generated by Django 2.0 on 2017-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_auto_20171227_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='other_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moduleinfo',
            name='simple_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='other_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='simple_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
