# Generated by Django 2.0.3 on 2018-04-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_auto_20180424_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='pro_name',
            new_name='project_name',
        ),
    ]
