# Generated by Django 2.0.3 on 2018-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_auto_20180608_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalk',
            name='debugtalk',
            field=models.TextField(default='\n                                1、请注意如果需要额外依赖包，请先pip install \n\n                                2、建议在python IDE环境编译通过，再Copy过来 \n\n                                3、当前只是个编辑界面，不提供校验代码功能哦 \n\n                                 '),
        ),
    ]
