# Generated by Django 2.0 on 2018-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_auto_20180104_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='module_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='extract',
            field=models.TextField(null=True),
        ),
    ]
