# Generated by Django 2.0 on 2018-01-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0004_auto_20180105_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='validate',
            field=models.TextField(null=True),
        ),
    ]
