# Generated by Django 2.0.3 on 2018-06-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0005_auto_20180608_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalk',
            name='debugtalk',
            field=models.TextField(),
        ),
    ]
