# Generated by Django 2.0 on 2018-01-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0005_auto_20180105_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=50)),
                ('belong_project', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('variables', models.TextField(null=True)),
                ('url', models.CharField(max_length=30)),
                ('data_type', models.CharField(max_length=10)),
                ('request', models.TextField(null=True)),
                ('headers', models.TextField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo')),
            ],
            options={
                'db_table': 'ConfigInfo',
            },
        ),
    ]
