# Generated by Django 2.0.3 on 2018-06-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0007_auto_20180612_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHooKInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('webhook_name', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ProjectInfo')),
            ],
            options={
                'verbose_name': 'WebHook信息',
                'db_table': 'WebHookInfo',
            },
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='interface_url',
            field=models.TextField(null=True, verbose_name='接口请求地址'),
        ),
        migrations.AddField(
            model_name='testcaseinfo',
            name='level',
            field=models.CharField(default='P0', max_length=20, verbose_name='用例级别'),
        ),
    ]
