# Generated by Django 2.0.3 on 2018-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0007_auto_20180612_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinfo',
            name='level',
            field=models.CharField(default='P0', max_length=20, verbose_name='用例级别'),
        ),
    ]
