# Generated by Django 2.0.3 on 2018-06-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0008_auto_20180623_2027'),
        ('ApiManager', '0008_merge_20180619_1837'),
    ]

    operations = [
    ]
